#!/bin/bash
# Website Blocker Module
# Blocks distracting websites to increase productivity

setup_website_blocker() {
    header "Setting Up Website Blocker"
    
    # Backup existing hosts file
    backup_file "/etc/hosts"
    
    # Define blocked websites
    local blocked_sites=(
        "facebook.com"
        "www.facebook.com"
        "m.facebook.com"
        "mobile.facebook.com"
        "touch.facebook.com"
        "instagram.com"
        "www.instagram.com"
        "twitter.com"
        "www.twitter.com"
        "x.com"
        "www.x.com"
        "tiktok.com"
        "www.tiktok.com"
        #"reddit.com"
        #"www.reddit.com"
        #"youtube.com"
        #"www.youtube.com"
        #"m.youtube.com"
    )
    
    # Create productivity hosts entries
    log "Creating productivity hosts entries..."
    local hosts_entries=""
    for site in "${blocked_sites[@]}"; do
        hosts_entries+="127.0.0.1 $site"$'\n'
        hosts_entries+="::1 $site"$'\n'
    done
    
    # Create temporary hosts file with productivity blocking
    log "Adding blocked sites to hosts file..."
    
    # Check if productivity section already exists
    if sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
        log "Removing existing productivity blocks..."
        sudo sed -i '/# PRODUCTIVITY BLOCK START/,/# PRODUCTIVITY BLOCK END/d' /etc/hosts
    fi
    
    # Add new productivity block
    {
        echo ""
        echo "# PRODUCTIVITY BLOCK START - Generated by Ubuntu GNOME Manager"
        echo "# Block distracting websites to increase productivity"
        echo "$hosts_entries"
        echo "# PRODUCTIVITY BLOCK END"
    } | sudo tee -a /etc/hosts >/dev/null
    
    log "✓ Website blocker configured"
    log "Blocked sites: ${blocked_sites[*]}"
    
    # Create management scripts
    create_blocker_scripts
    
    log "Website blocker setup complete"
}

# Create management scripts for easy enable/disable
create_blocker_scripts() {
    log "Creating website blocker management scripts..."
    
    # Create enable script
    cat > "$HOME/.local/bin/enable-website-blocker" << 'EOF'
#!/bin/bash
# Enable website blocking

if ! sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
    echo "❌ Website blocker not installed. Run the main setup first."
    exit 1
fi

# Check if already enabled
if ! sudo grep -q "^#127.0.0.1 facebook.com" /etc/hosts; then
    echo "✅ Website blocker is already enabled"
    exit 0
fi

# Enable blocking by uncommenting lines
sudo sed -i '/# PRODUCTIVITY BLOCK START/,/# PRODUCTIVITY BLOCK END/ s/^#\(127\.0\.0\.1\|::1\)/\1/' /etc/hosts

echo "🚫 Website blocker ENABLED - Distracting sites are now blocked"
echo "💡 Use 'disable-website-blocker' to temporarily disable"
EOF

    # Create disable script
    cat > "$HOME/.local/bin/disable-website-blocker" << 'EOF'
#!/bin/bash
# Disable website blocking temporarily

if ! sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
    echo "❌ Website blocker not installed. Run the main setup first."
    exit 1
fi

# Check if already disabled
if sudo grep -q "^#127.0.0.1 facebook.com" /etc/hosts; then
    echo "✅ Website blocker is already disabled"
    exit 0
fi

# Disable blocking by commenting lines
sudo sed -i '/# PRODUCTIVITY BLOCK START/,/# PRODUCTIVITY BLOCK END/ s/^\(127\.0\.0\.1\|::1\)/#\1/' /etc/hosts

echo "✅ Website blocker DISABLED - Sites are temporarily accessible"
echo "💡 Use 'enable-website-blocker' to re-enable blocking"
EOF

    # Create status script
    cat > "$HOME/.local/bin/website-blocker-status" << 'EOF'
#!/bin/bash
# Check website blocker status

if ! sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
    echo "❌ Website blocker not installed"
    exit 1
fi

if sudo grep -q "^127.0.0.1 facebook.com" /etc/hosts; then
    echo "🚫 Website blocker is ENABLED"
    echo ""
    echo "Blocked sites:"
    sudo grep -A 20 "# PRODUCTIVITY BLOCK START" /etc/hosts | grep "^127.0.0.1" | awk '{print "  - " $2}'
else
    echo "✅ Website blocker is DISABLED"
fi
EOF

    # Make scripts executable
    chmod +x "$HOME/.local/bin/enable-website-blocker"
    chmod +x "$HOME/.local/bin/disable-website-blocker" 
    chmod +x "$HOME/.local/bin/website-blocker-status"
    
    log "✓ Management scripts created:"
    log "  - enable-website-blocker"
    log "  - disable-website-blocker"
    log "  - website-blocker-status"
}

# Test website blocker functionality
test_website_blocker() {
    header "Testing Website Blocker"
    
    # Check if hosts file has productivity block
    if sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
        log "✓ Productivity block section exists in hosts file"
        
        # Check if blocking is active
        if sudo grep -q "^127.0.0.1 facebook.com" /etc/hosts; then
            log "✓ Website blocking is ACTIVE"
        else
            log "⚠️ Website blocking is DISABLED"
        fi
        
        # Count blocked sites
        local blocked_count
        blocked_count=$(sudo grep -c "^127.0.0.1.*facebook\|instagram\|twitter\|tiktok\|reddit\|youtube" /etc/hosts 2>/dev/null || echo "0")
        log "✓ Blocking $blocked_count sites"
        
    else
        warn "✗ Productivity block not found in hosts file"
    fi
    
    # Check management scripts
    local scripts=("enable-website-blocker" "disable-website-blocker" "website-blocker-status")
    for script in "${scripts[@]}"; do
        if [[ -x "$HOME/.local/bin/$script" ]]; then
            log "✓ $script script exists and is executable"
        else
            warn "✗ $script script missing or not executable"
        fi
    done
    
    log "Website blocker test complete"
}

# Remove website blocker
remove_website_blocker() {
    header "Removing Website Blocker"
    
    log "Removing productivity blocks from hosts file..."
    if sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
        sudo sed -i '/# PRODUCTIVITY BLOCK START/,/# PRODUCTIVITY BLOCK END/d' /etc/hosts
        log "✓ Productivity blocks removed from hosts file"
    else
        log "No productivity blocks found in hosts file"
    fi
    
    # Remove management scripts
    local scripts=("enable-website-blocker" "disable-website-blocker" "website-blocker-status")
    for script in "${scripts[@]}"; do
        if [[ -f "$HOME/.local/bin/$script" ]]; then
            rm "$HOME/.local/bin/$script"
            log "✓ Removed $script"
        fi
    done
    
    log "Website blocker removal complete"
}

# Add custom site to block list
add_blocked_site() {
    local site="$1"
    
    if [[ -z "$site" ]]; then
        error "Usage: add_blocked_site <domain>"
        return 1
    fi
    
    header "Adding $site to Block List"
    
    if ! sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
        error "Website blocker not installed. Run setup first."
        return 1
    fi
    
    # Check if site already blocked
    if sudo grep -q "127.0.0.1 $site" /etc/hosts; then
        warn "$site is already blocked"
        return 0
    fi
    
    # Add site before the end marker
    sudo sed -i "/# PRODUCTIVITY BLOCK END/i 127.0.0.1 $site" /etc/hosts
    sudo sed -i "/# PRODUCTIVITY BLOCK END/i ::1 $site" /etc/hosts
    
    log "✓ Added $site to block list"
}

# Remove site from block list
remove_blocked_site() {
    local site="$1"
    
    if [[ -z "$site" ]]; then
        error "Usage: remove_blocked_site <domain>"
        return 1
    fi
    
    header "Removing $site from Block List"
    
    if ! sudo grep -q "# PRODUCTIVITY BLOCK START" /etc/hosts; then
        error "Website blocker not installed"
        return 1
    fi
    
    # Remove site entries
    sudo sed -i "/# PRODUCTIVITY BLOCK START/,/# PRODUCTIVITY BLOCK END/ /127\.0\.0\.1 $site/d" /etc/hosts
    sudo sed -i "/# PRODUCTIVITY BLOCK START/,/# PRODUCTIVITY BLOCK END/ /::1 $site/d" /etc/hosts
    
    log "✓ Removed $site from block list"
}